"""add trade journal and reports

Revision ID: 5c051f3a6b8d
Revises: a1d1f7572f61
Create Date: 2026-06-23 01:57:54.122974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c051f3a6b8d'
down_revision: Union[str, Sequence[str], None] = 'a1d1f7572f61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trade_journals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('trade_type', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('entry_price', sa.Float(), nullable=True),
    sa.Column('exit_price', sa.Float(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('strategy', sa.Text(), nullable=True),
    sa.Column('mistake', sa.Text(), nullable=True),
    sa.Column('learning', sa.Text(), nullable=True),
    sa.Column('mood', sa.String(), nullable=True),
    sa.Column('tags', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trade_journals_id'), 'trade_journals', ['id'], unique=False)
    op.create_index(op.f('ix_trade_journals_symbol'), 'trade_journals', ['symbol'], unique=False)
    op.create_index(op.f('ix_trade_journals_user_id'), 'trade_journals', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trade_journals_user_id'), table_name='trade_journals')
    op.drop_index(op.f('ix_trade_journals_symbol'), table_name='trade_journals')
    op.drop_index(op.f('ix_trade_journals_id'), table_name='trade_journals')
    op.drop_table('trade_journals')
    # ### end Alembic commands ###
